import type { EditorElement } from "./editorTypes";

export interface LabelTemplate {
  id: string;
  name: string;
  description: string;
  elements: EditorElement[];
}

/** Posities voor 85×62 mm canvas (954×696 px). Grotere defaults voor leesbare print. */
export const BUILTIN_TEMPLATES: LabelTemplate[] = [
  {
    id: "datum",
    name: "Alleen datum",
    description: "Grote datumtekst",
    elements: [
      {
        id: "t-datum",
        type: "text",
        x: 40,
        y: 280,
        text: new Date().toLocaleDateString("nl-NL"),
        fontSize: 96,
        fontStyle: "bold",
        fill: "#000000",
        width: 874,
        align: "center",
      },
    ],
  },
  {
    id: "titel-regel",
    name: "Titel + regel",
    description: "Kop en ondertitel (IC-stijl)",
    elements: [
      {
        id: "t-title",
        type: "text",
        x: 40,
        y: 100,
        text: "Medicatienaam",
        fontSize: 72,
        fontStyle: "bold",
        fill: "#000000",
        width: 874,
        align: "center",
      },
      {
        id: "t-sub",
        type: "text",
        x: 40,
        y: 480,
        text: "Concentratie / toelichting",
        fontSize: 52,
        fontStyle: "normal",
        fill: "#000000",
        width: 874,
        align: "center",
      },
      {
        id: "frame",
        type: "rect",
        x: 20,
        y: 20,
        width: 914,
        height: 656,
        stroke: "#000000",
        strokeWidth: 5,
      },
    ],
  },
  {
    id: "adres",
    name: "Dosis + volume",
    description: "Twee kolommen onder titel",
    elements: [
      {
        id: "t-name",
        type: "text",
        x: 40,
        y: 60,
        text: "Product",
        fontSize: 64,
        fontStyle: "bold",
        fill: "#000000",
        width: 874,
        align: "center",
      },
      {
        id: "t-dose",
        type: "text",
        x: 80,
        y: 360,
        text: "100 mg",
        fontSize: 56,
        fontStyle: "bold",
        fill: "#000000",
        width: 360,
        align: "center",
      },
      {
        id: "t-vol",
        type: "text",
        x: 514,
        y: 360,
        text: "10 ml",
        fontSize: 56,
        fontStyle: "bold",
        fill: "#000000",
        width: 360,
        align: "center",
      },
      {
        id: "line-mid",
        type: "line",
        x: 0,
        y: 0,
        points: [477, 300, 477, 640],
        stroke: "#000000",
        strokeWidth: 3,
      },
    ],
  },
  {
    id: "medicatie-icoon",
    name: "Medicatie + icoon",
    description: "Naam, dosis en medisch kruis",
    elements: [
      {
        id: "icon-cross",
        type: "icon",
        x: 70,
        y: 80,
        iconId: "medical-cross",
        width: 110,
        height: 110,
      },
      {
        id: "t-med-name",
        type: "text",
        x: 210,
        y: 90,
        text: "Medicatienaam",
        fontSize: 64,
        fontStyle: "bold",
        fill: "#000000",
        width: 700,
        align: "left",
      },
      {
        id: "t-med-dose",
        type: "text",
        x: 210,
        y: 170,
        text: "100 mg / 10 ml",
        fontSize: 44,
        fontStyle: "normal",
        fill: "#000000",
        width: 700,
        align: "left",
      },
      {
        id: "t-med-note",
        type: "text",
        x: 40,
        y: 480,
        text: "Bereid:  —   Houdbaar tot:",
        fontSize: 40,
        fontStyle: "normal",
        fill: "#000000",
        width: 874,
        align: "left",
      },
    ],
  },
  {
    id: "eigendom",
    name: "Eigendom van",
    description: "Naam + icoon",
    elements: [
      {
        id: "icon-home",
        type: "icon",
        x: 70,
        y: 250,
        iconId: "home",
        width: 130,
        height: 130,
      },
      {
        id: "t-own",
        type: "text",
        x: 220,
        y: 255,
        text: "Eigendom van",
        fontSize: 48,
        fontStyle: "normal",
        fill: "#000000",
        width: 680,
        align: "left",
      },
      {
        id: "t-owner",
        type: "text",
        x: 220,
        y: 320,
        text: "Jouw naam",
        fontSize: 72,
        fontStyle: "bold",
        fill: "#000000",
        width: 680,
        align: "left",
      },
    ],
  },
];
